### PR TITLE
Detect detached elements during drag'n'drop

### LINKED ISSUE #14: Element could've already been detached from the DOM when "mouseup" is triggered
Trying to add a test for an app which uses [react-dnd](https://react-dnd.github.io) and in my case `drop target` node is removed from the DOM after the `drop` event is triggered.

At the time `mouseup` is triggered the node is no longer in the DOM and `cypress` returns an error.

```
CypressError: cy.trigger() failed because this element is detached from the DOM.
```

As I understand some implementations of DnD could listen for the `drop` event, some - for `mouseup` event and some for both.

According to the [cypress docs on conditional testing](https://docs.cypress.io/guides/core-concepts/conditional-testing.html#Definition) we can not implement a condition logic to checks if `drop target` node still exists in the DOM before triggering `mouseup` because it has been removed from the DOM asynchronously.

Can we update the command so it accepts another parameter `dropEvents` (with default value `["drop"]`) so a user can define specific event(s) to trigger?

On a separate note, not sure we need it to be an array.

If the proposed solution looks reasonable I can create a PR.

Full error:
```
CypressError: cy.trigger() failed because this element is detached from the DOM.

<div class="EmptyBlock_block__2auyt" data-cy="empty-block-placeholder" draggable="true"></div>

Cypress requires elements to be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.trigger()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom

All 3 subject validations failed on this subject.
```

### PR DESCRIPTION
**Pull request by bierik**
The drop event is split up in `drop`, `mouseup` and `pointerup` events.
When the target receives a `drop` event, is may be detached from the
DOM. So check if the elements is still in the DOM before proceeding the
further events in the drop chain.

Closes #14

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,9 +1,14 @@
 const dataTransfer = new DataTransfer()
 
+function isDetached(element) {
+  return element.closest('html')
```
Comment (andriibuts) [inline index.js]: @bierik, could you clarify the reason behind the function name?

It returns `truthy` value if an element has `html` as one of its parent - which means the element is attached to the DOM, so the function name should be `isAttached`. Though I may miss something :)

Comment (bierik) [reply index.js]: You are absolutely right the function should be `isAttached`. I changed it. Could you review again and test it?

Comment (andriibuts) [reply index.js]: It seems to work fine on my setup. Thanks!

**Comment by bierik** [comment]
@andriibuts new version 1.3.1 is released on npm -> https://www.npmjs.com/package/@4tw/cypress-drag-drop. Thank you very much for your contribution.
